### ISSUE TITLE
Position of Flash movie incorrect when CSS zoom is used

### ISSUE THREAD

**Issue by myitcv** [zeroclipboard/zeroclipboard#149]
When using ZeroClipboard with [reveal.js](https://github.com/hakimel/reveal.js) problems crop up because reveal.js uses CSS zoom.

This means that the calculation of the position of the glued element (via `_getDOMObjectPosition`) is incorrect. 

The following screenshot shows the problem visually. The red box is the repositioned Flash Movie object, even though the cursor is hovering over the button ("Copy to Clipboard...") to which it is 'glued' 

![zoom_problem](https://f.cloud.github.com/assets/3374574/489371/4da56682-b99a-11e2-87dd-57c4f0a57a4f.png)

**Comment by SeanZicari** [comment]
I've got some HTML that uses CSS transform rules, and the same positioning problem exists there, too. Here are the rules being applied to the body:

```css
@media (min-width: 768px) {
	body {
		transform: scale(0.75);
		-webkit-transform: scale(0.75);
		-moz-transform: scale(0.75);
		-ms-transform: scale(0.75);
		transform-origin: center 0;
		-webkit-transform-origin: center 0;
		-moz-transform-origin: center 0;
		-ms-transform-origin: center 0;

	}
}
```
