### ISSUE TITLE
Setting css style for ZeroClipboard when code is using pseudo-classes

### ISSUE THREAD

**Issue by edpichler** [zeroclipboard/zeroclipboard#177]
I have a button "Copy to clippboard" using ZeroClipboard. I can't find a way to configure the hover and active style for the button, once they is "freezed" because the transparent flash, so the button is not changing the style when the mouse is over.
But in my CSS, this behavior is made by pseudo-classes.

``` css
.red:hover {
    background-color: #CA3137;
}
.red:active {
    background-color: #CA3137;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.3) inset !important;
}
```

How can I configure ZeroClipboard to button change style when the mouse is over when use pseudo-classes?
