### ISSUE TITLE
CSS effect opacity not working

### ISSUE THREAD

**Issue by jaedb** [zeroclipboard/zeroclipboard#488]
Using the '.zeroclipboard-is-hover' to apply opacity effects to the underlying DOM element doesn't work. I have tested with other CSS effects (background, padding, etc) but opacity just doesn't want to work.

This is the code that I'm using:

``` css
.copy-to-clipboard {
    opacity: 0.5;
}

.copy-to-clipboard.zeroclipboard-is-hover {
    opacity 1; /* opacity doesn't seem to be parsed with zeroclipboard? */
}
```
